name: simple-warp
version: '${version}'
main: idan.dev.warp.WarpPluginLoader
api-version: 1.19
commands:
  warp:
    description: Teleport to a warp
  setWarp:
    description: Set a warp
  unWarp:
    description: Remove a warp
